name: pnpm test
on:
  push:
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [18]
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Run coverage
      run: pnpm coverage
    - name: Run build
      run: pnpm build